import {
  Code, ShieldCheck, Repeat, Terminal, FileCode, Palette, Zap, Shield, Globe, Cpu, Layout, Table, Image,
  Link, Share2, Search, FileText, BoxSelect, Square, Grid, Box, Play, Calculator, Type
} from 'lucide-react';

export const TOOLS = [
  { id: 'json-formatter', icon: Code, category: 'text' },
  { id: 'json-to-csv', icon: FileCode, category: 'text' },
  { id: 'csv-to-json', icon: FileCode, category: 'text' },
  { id: 'xml-formatter', icon: Code, category: 'text' },
  { id: 'yaml-validator', icon: FileCode, category: 'text' },
  { id: 'toml-validator', icon: FileCode, category: 'text' },
  { id: 'markdown-previewer', icon: FileCode, category: 'text' },
  { id: 'code-diff-checker', icon: Code, category: 'text' },
  { id: 'word-counter', icon: FileCode, category: 'text' },
  { id: 'lorem-ipsum', icon: FileCode, category: 'text' },
  { id: 'case-converter', icon: FileCode, category: 'text' },
  { id: 'slug-generator', icon: FileCode, category: 'text' },
  { id: 'string-reverse', icon: FileCode, category: 'text' },
  { id: 'duplicate-remover', icon: FileCode, category: 'text' },
  { id: 'whitespace-remover', icon: FileCode, category: 'text' },
  { id: 'ascii-art', icon: Palette, category: 'text' },
  { id: 'emoji-picker', icon: Palette, category: 'text' },
  { id: 'text-sorter', icon: FileCode, category: 'text' },
  { id: 'line-number-adder', icon: FileCode, category: 'text' },
  { id: 'find-replace', icon: FileCode, category: 'text' },
  { id: 'jwt-decoder', icon: ShieldCheck, category: 'data' },
  { id: 'base64-encoder', icon: Repeat, category: 'data' },
  { id: 'env-checker', icon: Terminal, category: 'data' },
  { id: 'regex-tester', icon: Terminal, category: 'dev' },
  { id: 'timestamp-converter', icon: Terminal, category: 'dev' },
  { id: 'api-tester', icon: Terminal, category: 'dev' },
  { id: 'curl-generator', icon: Terminal, category: 'dev' },
  { id: 'uuid-generator', icon: Terminal, category: 'dev' },
  { id: 'color-palette-generator', icon: Palette, category: 'design' },
  { id: 'image-to-base64', icon: Palette, category: 'design' },
  { id: 'css-gradient-generator', icon: Palette, category: 'design' },
  { id: 'sql-formatter', icon: FileCode, category: 'web' },
  { id: 'url-encoder', icon: Repeat, category: 'data' },
  { id: 'html-entity-encoder', icon: Code, category: 'web' },
  { id: 'jwt-builder', icon: ShieldCheck, category: 'data' },
  { id: 'md5-generator', icon: Shield, category: 'data' },
  { id: 'sha-generator', icon: Shield, category: 'data' },
  { id: 'bcrypt-generator', icon: ShieldCheck, category: 'data' },
  { id: 'argon2-generator', icon: ShieldCheck, category: 'data' },
  { id: 'hmac-generator', icon: Shield, category: 'data' },
  { id: 'morse-converter', icon: FileCode, category: 'text' },
  { id: 'base-converter', icon: Repeat, category: 'data' },
  { id: 'caesar-cipher', icon: Shield, category: 'data' },
  { id: 'rot13-encoder', icon: Repeat, category: 'data' },
  { id: 'punycode-converter', icon: Globe, category: 'web' },
  { id: 'unicode-inspector', icon: FileCode, category: 'text' },
  { id: 'html-color-to-hex', icon: Palette, category: 'design' },
  { id: 'aes-encryptor', icon: Shield, category: 'data' },
  { id: 'rsa-key-generator', icon: Shield, category: 'data' },
  { id: 'qrcode-decoder', icon: Palette, category: 'design' },
  // Phase 2: HTML Processing Batch
  { id: 'html-previewer', icon: Code, category: 'web' },
  { id: 'html-minifier', icon: Code, category: 'web' },
  { id: 'html-beautifier', icon: Code, category: 'web' },
  { id: 'html-to-markdown', icon: Repeat, category: 'web' },
  { id: 'markdown-to-html', icon: Repeat, category: 'web' },
  { id: 'html-to-jsx', icon: Code, category: 'web' },
  // Phase 3: Generators & SEO Batch
  { id: 'meta-tag-generator', icon: Globe, category: 'web' },
  { id: 'favicon-generator', icon: Image, category: 'web' },
  { id: 'robots-txt-generator', icon: ShieldCheck, category: 'web' },
  { id: 'sitemap-generator', icon: Globe, category: 'web' },
  { id: 'htaccess-generator', icon: Shield, category: 'web' },
  { id: 'iframe-generator', icon: Layout, category: 'web' },
  { id: 'html-table-generator', icon: Table, category: 'web' },
  // Phase 4: Web Utility Tools
  { id: 'og-previewer', icon: Share2, category: 'web' },
  { id: 'link-extractor', icon: Link, category: 'web' },
  { id: 'http-status-reference', icon: FileText, category: 'web' },
  { id: 'mime-type-finder', icon: Search, category: 'web' },
  { id: 'cookie-parser', icon: Table, category: 'web' },
  { id: 'user-agent-parser', icon: Cpu, category: 'web' },
  { id: 'url-parser', icon: Link, category: 'web' },
  // Phase 5: Visual CSS Tools
  { id: 'box-shadow-generator', icon: BoxSelect, category: 'design' },
  { id: 'border-radius-generator', icon: Square, category: 'design' },
  { id: 'flexbox-playground', icon: Layout, category: 'design' },
  { id: 'grid-generator', icon: Grid, category: 'design' },
  { id: 'glassmorphism-generator', icon: Image, category: 'design' },
  { id: 'neumorphism-generator', icon: Box, category: 'design' },
];

export const CATEGORIES = ['all', 'text', 'data', 'dev', 'design', 'web'];
