"use client"

import { useState, useCallback, useEffect } from 'react';
import { useTranslations } from 'next-intl';
import { Label } from '@/components/ui/label';
import { Button } from '@/components/ui/button';
import { Switch } from '@/components/ui/switch';
import { Copy, Trash2, Settings2, Info, Check } from 'lucide-react';
import { ToolCard } from '@/components/layout/tool-card';
import { CopyButton, DownloadButton, ToolActions, InfoBox, StatsDisplay, CodeTextarea } from '@/components/common';
import { useCopyToClipboard } from '@/hooks/use-copy-to-clipboard';

export function HtaccessGeneratorClient() {
  const t = useTranslations('tools.htaccess-generator');
  const commonT = useTranslations('common');
  const { copiedType, copyToClipboard } = useCopyToClipboard();
  
  const [formData, setFormData] = useState({ forceHttps: true, wwwRedirect: false, caching: true });
  const [output, setOutput] = useState('');

  const generateHtaccess = useCallback(() => {
    let lines = ['# Generated by DevTools Hub', 'RewriteEngine On', ''];
    if (formData.forceHttps) lines.push('# Force HTTPS', 'RewriteCond %{HTTPS} off', 'RewriteRule ^(.*)$ https://%{HTTP_HOST}%{REQUEST_URI} [L,R=301]', '');
    if (formData.wwwRedirect) lines.push('# Force WWW', 'RewriteCond %{HTTP_HOST} !^www\\. [NC]', 'RewriteRule ^(.*)$ http://www.%{HTTP_HOST}%{REQUEST_URI} [L,R=301]', '');
    if (formData.caching) lines.push('# Browser Caching', '<IfModule mod_expires.c>', '  ExpiresActive On', '  ExpiresDefault "access plus 1 month"', '  ExpiresByType text/html "access plus 1 day"', '  ExpiresByType image/x-icon "access plus 1 year"', '</IfModule>', '');
    setOutput(lines.join('\n'));
  }, [formData]);

  useEffect(() => { generateHtaccess(); }, [generateHtaccess]);

  const handleClear = () => setFormData({ forceHttps: false, wwwRedirect: false, caching: false });

  return (
    <div className="grid gap-6 md:grid-cols-3 items-start">
      <div className="md:col-span-2 grid gap-4 sm:grid-cols-2">
        <ToolCard 
          title={commonT('input')}
          action={<Button variant="ghost" size="icon" onClick={handleClear} title={commonT('clear')} className="h-6 w-6 hover:text-destructive"><Trash2 className="h-3 w-3" /></Button>}
          contentClassName="p-4 space-y-6"
        >
          <div className="flex items-center justify-between">
            <div className="space-y-1"><Label className="text-sm">{t('force_https')}</Label><p className="text-[10px] text-muted-foreground leading-tight">{t('force_https_desc')}</p></div>
            <Switch checked={formData.forceHttps} onCheckedChange={(val) => setFormData({ ...formData, forceHttps: val })} className="scale-90" />
          </div>
          <div className="flex items-center justify-between">
            <div className="space-y-1"><Label className="text-sm">{t('www_redirect')}</Label><p className="text-[10px] text-muted-foreground leading-tight">{t('www_redirect_desc')}</p></div>
            <Switch checked={formData.wwwRedirect} onCheckedChange={(val) => setFormData({ ...formData, wwwRedirect: val })} className="scale-90" />
          </div>
          <div className="flex items-center justify-between">
            <div className="space-y-1"><Label className="text-sm">{t('caching')}</Label><p className="text-[10px] text-muted-foreground leading-tight">{t('caching_desc')}</p></div>
            <Switch checked={formData.caching} onCheckedChange={(val) => setFormData({ ...formData, caching: val })} className="scale-90" />
          </div>
        </ToolCard>

        <ToolCard 
          title={commonT('ui.result')}
          action={<Button variant="ghost" size="sm" onClick={() => copyToClipboard(output, 'htaccess')} className="h-6 px-2 text-[10px] gap-1.5">{copiedType === 'htaccess' ? <Check className="h-3 w-3 text-green-500" /> : <Copy className="h-3 w-3" />}{commonT('copy')}</Button>}
          contentClassName="p-0 flex flex-col h-full bg-muted/20 min-h-[400px]"
        >
          <pre className="flex-1 font-mono text-[11px] p-4 overflow-auto whitespace-pre-wrap leading-relaxed text-foreground bg-transparent">{output}</pre>
        </ToolCard>
      </div>

      <div className="md:col-span-1 space-y-4">
        <ToolCard title={commonT('ui.options')} icon={Settings2} contentClassName="p-4 space-y-4">
          <div className="flex gap-2.5 items-start p-3 rounded-md bg-muted/30 border border-border">
            <Info className="h-3.5 w-3.5 text-muted-foreground mt-0.5 shrink-0" />
            <p className="text-[10px] text-muted-foreground leading-normal">{t('article').split('.')[0]}.</p>
          </div>
          <div className="p-3 rounded-md bg-amber-500/10 border border-amber-500/20">
            <p className="text-[10px] text-amber-600 font-medium">Apache only! Not compatible with Nginx.</p>
          </div>
        </ToolCard>
      </div>
    </div>
  );
}
