'use client';

import { useState, useCallback, useEffect } from 'react';
import { useTranslations } from 'next-intl';
import { Card, CardContent, CardHeader, CardTitle } from '@/components/ui/card';
import { Label } from '@/components/ui/label';
import { Button } from '@/components/ui/button';
import { Switch } from '@/components/ui/switch';
import { Copy, Trash2, Settings2, Info, Check } from 'lucide-react';
import { ToolNavigation } from '@/components/tool-navigation';

export function HtaccessGeneratorClient() {
  const t = useTranslations('tools.htaccess-generator');
  const commonT = useTranslations('common');
  
  const [formData, setFormData] = useState({
    forceHttps: true,
    wwwRedirect: false,
    caching: true,
  });
  
  const [output, setOutput] = useState('');
  const [copied, setCopied] = useState(false);

  const generateHtaccess = useCallback(() => {
    let lines = [];
    lines.push('# Generated by DevTools Hub');
    lines.push('RewriteEngine On');
    lines.push('');
    
    if (formData.forceHttps) {
      lines.push('# Force HTTPS');
      lines.push('RewriteCond %{HTTPS} off');
      lines.push('RewriteRule ^(.*)$ https://%{HTTP_HOST}%{REQUEST_URI} [L,R=301]');
      lines.push('');
    }
    
    if (formData.wwwRedirect) {
      lines.push('# Force WWW');
      lines.push('RewriteCond %{HTTP_HOST} !^www\\. [NC]');
      lines.push('RewriteRule ^(.*)$ http://www.%{HTTP_HOST}%{REQUEST_URI} [L,R=301]');
      lines.push('');
    }
    
    if (formData.caching) {
      lines.push('# Browser Caching');
      lines.push('<IfModule mod_expires.c>');
      lines.push('  ExpiresActive On');
      lines.push('  ExpiresDefault "access plus 1 month"');
      lines.push('  ExpiresByType text/html "access plus 1 day"');
      lines.push('  ExpiresByType image/x-icon "access plus 1 year"');
      lines.push('</IfModule>');
      lines.push('');
    }
    
    setOutput(lines.join('\n'));
  }, [formData]);

  useEffect(() => {
    generateHtaccess();
  }, [generateHtaccess]);

  const copyToClipboard = () => {
    navigator.clipboard.writeText(output);
    setCopied(true);
    setTimeout(() => setCopied(false), 2000);
  };

  const handleClear = () => {
    setFormData({
      forceHttps: false,
      wwwRedirect: false,
      caching: false,
    });
  };

  return (
    <div className="space-y-12">
      <div className="grid gap-6 lg:grid-cols-12 items-start">
        <div className="lg:col-span-9 grid gap-4 md:grid-cols-2">
          {/* Form Area */}
          <div className="flex flex-col gap-2">
            <div className="flex items-center justify-between px-1">
              <div className="flex items-center gap-2">
                <Label className="text-[11px] font-semibold uppercase tracking-wider text-muted-foreground">{commonT('input')}</Label>
              </div>
              <Button variant="ghost" size="icon" onClick={handleClear} title={commonT('clear')} className="h-6 w-6 text-muted-foreground hover:text-destructive">
                <Trash2 className="h-3 w-3" />
              </Button>
            </div>
            <Card className="border border-border shadow-none rounded-md p-4 bg-background space-y-6">
              <div className="flex items-center justify-between">
                <div className="space-y-1">
                  <Label className="text-sm">{t('force_https')}</Label>
                  <p className="text-[10px] text-muted-foreground leading-tight">{t('force_https_desc')}</p>
                </div>
                <Switch 
                  checked={formData.forceHttps} 
                  onCheckedChange={(val) => setFormData({ ...formData, forceHttps: val })} 
                  className="scale-90"
                />
              </div>
              <div className="flex items-center justify-between">
                <div className="space-y-1">
                  <Label className="text-sm">{t('www_redirect')}</Label>
                  <p className="text-[10px] text-muted-foreground leading-tight">{t('www_redirect_desc')}</p>
                </div>
                <Switch 
                  checked={formData.wwwRedirect} 
                  onCheckedChange={(val) => setFormData({ ...formData, wwwRedirect: val })} 
                  className="scale-90"
                />
              </div>
              <div className="flex items-center justify-between">
                <div className="space-y-1">
                  <Label className="text-sm">{t('caching')}</Label>
                  <p className="text-[10px] text-muted-foreground leading-tight">{t('caching_desc')}</p>
                </div>
                <Switch 
                  checked={formData.caching} 
                  onCheckedChange={(val) => setFormData({ ...formData, caching: val })} 
                  className="scale-90"
                />
              </div>
            </Card>
          </div>

          {/* Output Area */}
          <div className="flex flex-col gap-2">
            <div className="flex items-center justify-between px-1">
              <div className="flex items-center gap-2">
                <Label className="text-[11px] font-semibold uppercase tracking-wider text-muted-foreground">{commonT('ui.result')}</Label>
              </div>
              <Button 
                variant="ghost" 
                size="sm" 
                onClick={copyToClipboard}
                className="h-6 px-2 text-[10px] gap-1.5 text-muted-foreground hover:text-foreground transition-colors"
              >
                {copied ? <Check className="h-3 w-3 text-green-500" /> : <Copy className="h-3 w-3" />}
                {commonT('copy')}
              </Button>
            </div>
            <Card className="flex flex-col h-full border border-border shadow-none rounded-md overflow-hidden bg-muted/20 min-h-[400px]">
              <pre className="flex-1 font-mono text-[11px] p-4 overflow-auto whitespace-pre-wrap leading-relaxed text-foreground bg-transparent">
                {output}
              </pre>
            </Card>
          </div>
        </div>

        {/* Sidebar Settings */}
        <div className="lg:col-span-3 space-y-4">
          <Card className="border border-border shadow-none rounded-md bg-background">
            <CardHeader className="py-3 px-4 border-b">
              <CardTitle className="text-xs font-semibold flex items-center gap-2">
                <Settings2 className="h-3.5 w-3.5" />
                {commonT('ui.options')}
              </CardTitle>
            </CardHeader>
            <CardContent className="p-4 space-y-4">
              <div className="flex gap-2.5 items-start p-3 rounded-md bg-muted/30 border border-border">
                <Info className="h-3.5 w-3.5 text-muted-foreground mt-0.5 shrink-0" />
                <p className="text-[10px] text-muted-foreground leading-normal">
                  {t('article').split('.')[0]}.
                </p>
              </div>
              <div className="p-3 rounded-md bg-amber-500/10 border border-amber-500/20">
                <p className="text-[10px] text-amber-600 font-medium">
                  Apache only! Not compatible with Nginx.
                </p>
              </div>
            </CardContent>
          </Card>
        </div>
      </div>
      <ToolNavigation currentToolId="htaccess-generator" />
    </div>
  );
}
